version: '2.0'

services:
  laravel:
    build: .
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: your_database_name
      DB_USERNAME: your_database_username
      DB_PASSWORD: your_database_password

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_username
      MYSQL_PASSWORD: your_database_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
