version: '2.0'

services:

  laravel-app-01:
    container_name: laravel-app-01
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      #- ./laravel-app-01:/var/www/html
      - /var/jenkins_home/workspace/TEST_3/laravel-app-01:/var/www/html 
    ports:
      - "9000:9000"
    depends_on:
      - mysql_db
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    volumes:
#      - ./laravel.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt
#      - ./nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key
#      - ./laravel-app-01:/var/www/html 
#    ports:
#      - "8081:80"
#      - "443:443"
#    depends_on:
#      - laravel-app-01
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Irma_Service@2024
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: Lar@vel_User_P@ssword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=Irma_Service@2024
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=Lar@vel_User_P@ssword
    ports:
      - "9002:80"
    depends_on:
      - mysql_db

volumes:
  mysql_data:
